# This is a basic workflow to help you get started with Actions

name: Deploy to Azure

on:
  issues:
    types: [labeled]

jobs:
  deploy:
    if: contains(github.event.issue.labels.*.name, 'approved')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: whiteducksoftware/azure-arm-action-js@v1
        with:
          resourceGroupName: github-actions-rg
          templateLocation: ./101-webapp-linux-node/azuredeploy.json
