name: TEST

on:
  project_card

jobs:
  update-project:
    if: github.event.action == 'moved'
    runs-on: [laptop]
    steps:
      - name: Store column id
        env:
          TO_COLUM: ${{ github.event.project_card.column_id}}          
        run: echo "$TO_COLUMN"
    