name: TEST

on:
  project_card
env:
  COL_TODO: 'To do'
  COL_INPG: 'In progress'
  COL_DONE: 'Done'
jobs:
  update-project:
    if: github.event.action == 'moved'
    runs-on: [laptop]
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const {column_id } = context.payload.project_card;
            console.log(context.payload);
            
            let { data: { name } } = await github.projects.getColumn({
              column_id,
            });

            
            const { COL_TODO, COL_INPG, COL_DONE} = process.env;
            switch (name) {
              case COL_TODO:
                console.log("New project requested");
                break;
              case COL_INPG:
                console.log("Start new project");
                break;
              case COL_DONE:
                console.log("Close project");
                break;
              default:
                console.log(`Column ${name} not present. Skipping...`); 
                break;
            }            
    