name: TEST

on:
  project_card
env:
  COL_TODO: 'To do'
  COL_INPG: 'In progress'
  COL_DONE: 'Done'
jobs:
  update-project:
    if: github.event.action == 'moved'
    runs-on: [laptop]
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            console.log(context)
    